In [1]:
from models.Marigold import MarigoldPipeline
import torch
import diffusers

ag = vars(MarigoldPipeline.from_pretrained("prs-eth/marigold-depth-lcm-v1-0", variant="fp16", torch_dtype=torch.float16))
model = MarigoldPipeline(diffusers.UNet2DConditionModel(**vars(ag['unet'])['_internal_dict']),
                         ag['vae'],
                         ag['scheduler'],
                         ag['text_encoder'],
                         ag['tokenizer'],
                         ag['scale_invariant'],
                         ag['shift_invariant'],
                         ag['default_denoising_steps'],
                         ag['default_processing_resolution'],
                         ag['empty_text_embed'])

c:\Users\micha\anaconda3\envs\pytorch-env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\micha\anaconda3\envs\pytorch-env\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|██████████| 5/5 [00:01<00:00,  4.63it/s]


In [3]:
for i in vars(pipe)['text_encoder'].parameters():
    print(i)
    break

Parameter containing:
tensor([[-0.0019, -0.0093,  0.0056,  ...,  0.0012, -0.0116,  0.0078],
        [ 0.0168,  0.0025, -0.0092,  ...,  0.0093, -0.0169,  0.0168],
        [-0.0087, -0.0275,  0.0082,  ..., -0.0155,  0.0097, -0.0119],
        ...,
        [-0.0038,  0.0344,  0.0041,  ...,  0.0065, -0.0116, -0.0079],
        [ 0.0004, -0.0038,  0.0039,  ..., -0.0008,  0.0012,  0.0006],
        [ 0.0034, -0.0028,  0.0003,  ..., -0.0032,  0.0009,  0.0016]],
       dtype=torch.float16, requires_grad=True)


In [2]:
transformers.CLIPTokenizer()

TypeError: CLIPTokenizer.__init__() missing 2 required positional arguments: 'vocab_file' and 'merges_file'

In [9]:
(vars(vars(pipe)['tokenizer']))['nlp']

In [19]:
for j in vars(pipe).keys():
    print(j)
    if j == '_internal_dict':
        for i in vars(pipe)[j].keys():
            print('\t',i, vars(vars(pipe)[j])[i])
        continue
    
    if j in ['text_encoder', 'tokenizer']:
        for i in vars(vars(pipe)[j]).keys():
            print('\t',i, vars(vars(pipe)[j])[i])
        continue
    
    # if j in ['scale_invariant', 'shift_invariant', 'default_denoising_steps']:
        # print('\t', vars(pipe)[j])
        # continue
    try:
        for i in vars(vars(pipe)[j])['_internal_dict'].keys():
            print('\t',i, vars(vars(pipe)[j])['_internal_dict'][i])
    except TypeError:
         print('\t', vars(pipe)[j])

_internal_dict
	 unet ('diffusers', 'UNet2DConditionModel')
	 vae ('diffusers', 'AutoencoderKL')
	 scheduler ('diffusers', 'LCMScheduler')
	 text_encoder ('transformers', 'CLIPTextModel')
	 tokenizer ('transformers', 'CLIPTokenizer')
	 scale_invariant True
	 shift_invariant True
	 default_denoising_steps 1
	 default_processing_resolution 768
	 _name_or_path prs-eth/marigold-depth-lcm-v1-0
unet
	 sample_size 96
	 in_channels 8
	 out_channels 4
	 center_input_sample False
	 flip_sin_to_cos True
	 freq_shift 0
	 down_block_types ['CrossAttnDownBlock2D', 'CrossAttnDownBlock2D', 'CrossAttnDownBlock2D', 'DownBlock2D']
	 mid_block_type UNetMidBlock2DCrossAttn
	 up_block_types ['UpBlock2D', 'CrossAttnUpBlock2D', 'CrossAttnUpBlock2D', 'CrossAttnUpBlock2D']
	 only_cross_attention False
	 block_out_channels [320, 640, 1280, 1280]
	 layers_per_block 2
	 downsample_padding 1
	 mid_block_scale_factor 1
	 dropout 0.0
	 act_fn silu
	 norm_num_groups 32
	 norm_eps 1e-05
	 cross_attention_dim 1024
	 tra

In [ ]:
unet = diffusers.UNet2DConditionModel(**vars(vars(pipe)['unet'])['_internal_dict'])
unet_default = diffusers.UNet2DConditionModel()

In [ ]:
for i in unet.parameters():
    print(i)
    break

Parameter containing:
tensor([[[[-9.2745e-03, -1.1445e-02, -5.6227e-02],
          [-1.1155e-01,  4.4297e-02,  7.7162e-02],
          [-4.4564e-02, -5.6962e-02, -3.8172e-02]],

         [[ 4.9318e-02,  9.5458e-02,  8.3053e-02],
          [-8.4483e-02,  1.1676e-01,  9.5850e-02],
          [ 1.0813e-01,  1.9707e-02, -1.0826e-01]],

         [[ 2.0888e-02,  1.0091e-01,  4.3792e-02],
          [ 3.8491e-02,  3.5890e-03, -7.0006e-02],
          [ 1.1254e-01, -1.1666e-01, -4.0829e-02]],

         ...,

         [[-1.0212e-01, -1.7729e-02,  3.1060e-02],
          [ 9.7128e-02,  6.3890e-02,  4.9450e-02],
          [-5.6970e-02,  7.2339e-02, -8.4551e-02]],

         [[ 3.5165e-03,  2.0402e-02, -6.9993e-02],
          [ 1.8166e-02, -6.0921e-02,  7.8180e-02],
          [ 6.0789e-02,  6.2770e-04,  4.8692e-02]],

         [[-8.3019e-02, -3.8227e-02, -7.2167e-03],
          [ 1.0039e-01, -7.1294e-02, -1.4598e-02],
          [ 9.7633e-02,  4.7542e-02,  4.8780e-02]]],


        [[[-2.2423e-02,  1.0717

In [ ]:
ag['unet'].parameters()

<generator object Module.parameters at 0x000001B38F07A6C0>

In [ ]:
for i in ag['unet'].parameters():
    print(i)
    break


Parameter containing:
tensor([[[[-0.0199,  0.0038,  0.0355],
          [-0.0098, -0.0702,  0.0526],
          [-0.0053, -0.0073,  0.0157]],

         [[ 0.0221, -0.0306,  0.0028],
          [ 0.0699, -0.0546, -0.0206],
          [ 0.0002, -0.0045,  0.0061]],

         [[ 0.0155, -0.0073,  0.0220],
          [-0.0141, -0.0150,  0.0180],
          [-0.0040, -0.0043, -0.0103]],

         ...,

         [[ 0.0217, -0.0287,  0.0038],
          [ 0.0548, -0.0410, -0.0148],
          [ 0.0105, -0.0022,  0.0050]],

         [[-0.0005, -0.0122,  0.0063],
          [-0.0104,  0.0262,  0.0164],
          [-0.0044, -0.0034, -0.0089]],

         [[ 0.0144, -0.0120,  0.0133],
          [ 0.0021, -0.0489,  0.0309],
          [-0.0009, -0.0074,  0.0103]]],


        [[[ 0.0017, -0.0017, -0.0195],
          [ 0.0076,  0.0206,  0.0458],
          [-0.0017,  0.0049,  0.0023]],

         [[-0.0013,  0.0036, -0.0087],
          [ 0.0016,  0.0270,  0.0042],
          [-0.0067,  0.0106,  0.0104]],

         

In [ ]:

for i in unet.parameters():
    print(i)
    break

Parameter containing:
tensor([[[[-9.2745e-03, -1.1445e-02, -5.6227e-02],
          [-1.1155e-01,  4.4297e-02,  7.7162e-02],
          [-4.4564e-02, -5.6962e-02, -3.8172e-02]],

         [[ 4.9318e-02,  9.5458e-02,  8.3053e-02],
          [-8.4483e-02,  1.1676e-01,  9.5850e-02],
          [ 1.0813e-01,  1.9707e-02, -1.0826e-01]],

         [[ 2.0888e-02,  1.0091e-01,  4.3792e-02],
          [ 3.8491e-02,  3.5890e-03, -7.0006e-02],
          [ 1.1254e-01, -1.1666e-01, -4.0829e-02]],

         ...,

         [[-1.0212e-01, -1.7729e-02,  3.1060e-02],
          [ 9.7128e-02,  6.3890e-02,  4.9450e-02],
          [-5.6970e-02,  7.2339e-02, -8.4551e-02]],

         [[ 3.5165e-03,  2.0402e-02, -6.9993e-02],
          [ 1.8166e-02, -6.0921e-02,  7.8180e-02],
          [ 6.0789e-02,  6.2770e-04,  4.8692e-02]],

         [[-8.3019e-02, -3.8227e-02, -7.2167e-03],
          [ 1.0039e-01, -7.1294e-02, -1.4598e-02],
          [ 9.7633e-02,  4.7542e-02,  4.8780e-02]]],


        [[[-2.2423e-02,  1.0717